spring:
  application:
    name: customers-service
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/petclinic}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    exclude: docker
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    sleuth:
      enabled: false
    zipkin:
      enabled: false

eureka:
  client:
    enabled: false
  instance:
    enabled: false

server:
  port: 8081




